
export const styles = {
  container: 'bg-gradient-to-b from-[#1c1b18] via-[#1a1917] to-black min-h-screen text-[#ffe36e] font-[Corleone] overflow-x-hidden',
  heading: 'text-center text-4xl sm:text-5xl md:text-6xl font-bold tracking-widest mb-10 text-shadow-lg',
  grid: 'mx-auto max-w-6xl grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-12 md:gap-16 px-4',
  card: 'pricing-card menu-card p-8 bg-gradient-to-br from-[#2a2a2a] via-[#252525] to-[#1f1f1f] rounded-2xl shadow-2xl shadow-yellow-400/30 border-2 border-yellow-500/60 relative transition-all duration-500 hover:shadow-yellow-400/50 cursor-pointer transform-gpu',
  tierTitle: 'text-2xl md:text-3xl mb-3 text-white font-bold tracking-wide',
  tierPrice: 'text-2xl font-bold mb-2 drop-shadow-lg',
  tierTarget: 'text-sm italic text-neutral-300 mb-4 leading-relaxed',
  tierOverview: 'text-base text-neutral-200 mb-8 leading-relaxed',
  ctaButton: 'uppercase tracking-wider font-bold px-6 py-4 rounded-lg text-black hover:opacity-90 text-sm w-full mt-4 bg-gradient-to-r from-yellow-300 to-red-500 shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-105 border-2 border-black hover:border-yellow-400',
  pauliImage: 'cursor-pointer hover:drop-shadow-xl transition-all duration-500 mt-12 max-w-xs mx-auto pauli-parallax',
  footer: 'text-center mt-32 text-sm text-neutral-400 pb-10 max-w-xl mx-auto text-balance leading-relaxed',
  heroContainer: 'relative overflow-hidden bg-gradient-to-b from-black via-[#1c1b18] to-[#1a1917] py-20 min-h-screen flex items-center',
  heroContent: 'relative z-10 max-w-6xl mx-auto px-6 text-center',
  heroImageWrapper: 'relative group cursor-pointer pauli-parallax mb-8',
  heroTitle: 'text-5xl md:text-7xl font-bold text-[#ffe36e] mb-6 tracking-wider drop-shadow-2xl text-shadow-yellow',
  heroSubtitle: 'text-xl md:text-2xl text-[#ffe36e] mb-8 leading-relaxed max-w-3xl mx-auto',
  heroButton: 'bg-gradient-to-r from-[#ffe36e] via-yellow-500 to-red-500 hover:from-yellow-500 hover:to-red-600 text-black px-8 py-4 rounded-lg font-bold transition-all duration-300 hover:scale-105 shadow-2xl border-2 border-black hover:border-yellow-400 text-lg tracking-wide',
  glowEffect: 'hero-glow absolute inset-0 bg-gradient-to-r from-yellow-400/20 via-red-500/20 to-yellow-400/20 rounded-full blur-xl',
  backgroundPattern: 'absolute inset-0 opacity-5 bg-[repeating-linear-gradient(45deg,transparent,transparent_50px,rgba(255,215,0,0.1)_50px,rgba(255,215,0,0.1)_100px)]',
};
